// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/started (interfaces: AccrualStartedEventsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockAccrualStartedEventsRepository is a mock of AccrualStartedEventsRepository interface.
type MockAccrualStartedEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualStartedEventsRepositoryMockRecorder
}

// MockAccrualStartedEventsRepositoryMockRecorder is the mock recorder for MockAccrualStartedEventsRepository.
type MockAccrualStartedEventsRepositoryMockRecorder struct {
	mock *MockAccrualStartedEventsRepository
}

// NewMockAccrualStartedEventsRepository creates a new mock instance.
func NewMockAccrualStartedEventsRepository(ctrl *gomock.Controller) *MockAccrualStartedEventsRepository {
	mock := &MockAccrualStartedEventsRepository{ctrl: ctrl}
	mock.recorder = &MockAccrualStartedEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualStartedEventsRepository) EXPECT() *MockAccrualStartedEventsRepositoryMockRecorder {
	return m.recorder
}

// ReserveEvent mocks base method.
func (m *MockAccrualStartedEventsRepository) ReserveEvent(arg0 context.Context, arg1 string) (*models.AccrualEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveEvent", arg0, arg1)
	ret0, _ := ret[0].(*models.AccrualEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveEvent indicates an expected call of ReserveEvent.
func (mr *MockAccrualStartedEventsRepositoryMockRecorder) ReserveEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveEvent", reflect.TypeOf((*MockAccrualStartedEventsRepository)(nil).ReserveEvent), arg0, arg1)
}

// SetState mocks base method.
func (m *MockAccrualStartedEventsRepository) SetState(arg0 context.Context, arg1, arg2 string, arg3 ...*sql.Tx) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetState", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockAccrualStartedEventsRepositoryMockRecorder) SetState(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockAccrualStartedEventsRepository)(nil).SetState), varargs...)
}
