// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_outbox/order_events/created (interfaces: OrderCreatedEventsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockOrderCreatedEventsRepository is a mock of OrderCreatedEventsRepository interface.
type MockOrderCreatedEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCreatedEventsRepositoryMockRecorder
}

// MockOrderCreatedEventsRepositoryMockRecorder is the mock recorder for MockOrderCreatedEventsRepository.
type MockOrderCreatedEventsRepositoryMockRecorder struct {
	mock *MockOrderCreatedEventsRepository
}

// NewMockOrderCreatedEventsRepository creates a new mock instance.
func NewMockOrderCreatedEventsRepository(ctrl *gomock.Controller) *MockOrderCreatedEventsRepository {
	mock := &MockOrderCreatedEventsRepository{ctrl: ctrl}
	mock.recorder = &MockOrderCreatedEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCreatedEventsRepository) EXPECT() *MockOrderCreatedEventsRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockOrderCreatedEventsRepository) BeginTx(arg0 context.Context, arg1 *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", arg0, arg1)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockOrderCreatedEventsRepositoryMockRecorder) BeginTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockOrderCreatedEventsRepository)(nil).BeginTx), arg0, arg1)
}

// CommitTX mocks base method.
func (m *MockOrderCreatedEventsRepository) CommitTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTX indicates an expected call of CommitTX.
func (mr *MockOrderCreatedEventsRepositoryMockRecorder) CommitTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTX", reflect.TypeOf((*MockOrderCreatedEventsRepository)(nil).CommitTX), arg0)
}

// ReserveNewOrderEvent mocks base method.
func (m *MockOrderCreatedEventsRepository) ReserveNewOrderEvent(arg0 context.Context, arg1 string, arg2 *sql.Tx) (*models.OrderEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveNewOrderEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.OrderEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveNewOrderEvent indicates an expected call of ReserveNewOrderEvent.
func (mr *MockOrderCreatedEventsRepositoryMockRecorder) ReserveNewOrderEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveNewOrderEvent", reflect.TypeOf((*MockOrderCreatedEventsRepository)(nil).ReserveNewOrderEvent), arg0, arg1, arg2)
}

// RollbackTX mocks base method.
func (m *MockOrderCreatedEventsRepository) RollbackTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTX indicates an expected call of RollbackTX.
func (mr *MockOrderCreatedEventsRepositoryMockRecorder) RollbackTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTX", reflect.TypeOf((*MockOrderCreatedEventsRepository)(nil).RollbackTX), arg0)
}

// Send mocks base method.
func (m *MockOrderCreatedEventsRepository) Send(arg0 context.Context, arg1 *models.OrderEvent, arg2 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockOrderCreatedEventsRepositoryMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOrderCreatedEventsRepository)(nil).Send), arg0, arg1, arg2)
}
