// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_outbox/orders/created (interfaces: OrderCreatedEventsPublisher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockOrderCreatedEventsPublisher is a mock of OrderCreatedEventsPublisher interface.
type MockOrderCreatedEventsPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCreatedEventsPublisherMockRecorder
}

// MockOrderCreatedEventsPublisherMockRecorder is the mock recorder for MockOrderCreatedEventsPublisher.
type MockOrderCreatedEventsPublisherMockRecorder struct {
	mock *MockOrderCreatedEventsPublisher
}

// NewMockOrderCreatedEventsPublisher creates a new mock instance.
func NewMockOrderCreatedEventsPublisher(ctrl *gomock.Controller) *MockOrderCreatedEventsPublisher {
	mock := &MockOrderCreatedEventsPublisher{ctrl: ctrl}
	mock.recorder = &MockOrderCreatedEventsPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCreatedEventsPublisher) EXPECT() *MockOrderCreatedEventsPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockOrderCreatedEventsPublisher) Publish(arg0 context.Context, arg1 *models.OrderEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockOrderCreatedEventsPublisherMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockOrderCreatedEventsPublisher)(nil).Publish), arg0, arg1)
}
