// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/started/commands (interfaces: OrderFSM)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
	entities "github.com/vysogota0399/gophermart_billing/internal/server/entities"
)

// MockOrderFSM is a mock of OrderFSM interface.
type MockOrderFSM struct {
	ctrl     *gomock.Controller
	recorder *MockOrderFSMMockRecorder
}

// MockOrderFSMMockRecorder is the mock recorder for MockOrderFSM.
type MockOrderFSMMockRecorder struct {
	mock *MockOrderFSM
}

// NewMockOrderFSM creates a new mock instance.
func NewMockOrderFSM(ctrl *gomock.Controller) *MockOrderFSM {
	mock := &MockOrderFSM{ctrl: ctrl}
	mock.recorder = &MockOrderFSMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderFSM) EXPECT() *MockOrderFSMMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockOrderFSM) Start(arg0 context.Context, arg1 entities.OrderFsmOption) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockOrderFSMMockRecorder) Start(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockOrderFSM)(nil).Start), arg0, arg1)
}
