// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/server/commands (interfaces: CreateOrderService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
	create_order "github.com/vysogota0399/gophermart_protos/gen/commands/create_order"
)

// MockCreateOrderService is a mock of CreateOrderService interface.
type MockCreateOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateOrderServiceMockRecorder
}

// MockCreateOrderServiceMockRecorder is the mock recorder for MockCreateOrderService.
type MockCreateOrderServiceMockRecorder struct {
	mock *MockCreateOrderService
}

// NewMockCreateOrderService creates a new mock instance.
func NewMockCreateOrderService(ctrl *gomock.Controller) *MockCreateOrderService {
	mock := &MockCreateOrderService{ctrl: ctrl}
	mock.recorder = &MockCreateOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateOrderService) EXPECT() *MockCreateOrderServiceMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockCreateOrderService) Call(arg0 context.Context, arg1 *create_order.NewOrder) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0, arg1)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockCreateOrderServiceMockRecorder) Call(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockCreateOrderService)(nil).Call), arg0, arg1)
}
