// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/finished/commands (interfaces: AccrualCreator)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
	entities "github.com/vysogota0399/gophermart_billing/internal/server/entities"
)

// MockAccrualCreator is a mock of AccrualCreator interface.
type MockAccrualCreator struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualCreatorMockRecorder
}

// MockAccrualCreatorMockRecorder is the mock recorder for MockAccrualCreator.
type MockAccrualCreatorMockRecorder struct {
	mock *MockAccrualCreator
}

// NewMockAccrualCreator creates a new mock instance.
func NewMockAccrualCreator(ctrl *gomock.Controller) *MockAccrualCreator {
	mock := &MockAccrualCreator{ctrl: ctrl}
	mock.recorder = &MockAccrualCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualCreator) EXPECT() *MockAccrualCreatorMockRecorder {
	return m.recorder
}

// CostAccrualed mocks base method.
func (m *MockAccrualCreator) CostAccrualed(arg0 context.Context, arg1 int64, arg2 entities.OrderFsmOption) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CostAccrualed", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CostAccrualed indicates an expected call of CostAccrualed.
func (mr *MockAccrualCreatorMockRecorder) CostAccrualed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CostAccrualed", reflect.TypeOf((*MockAccrualCreator)(nil).CostAccrualed), arg0, arg1, arg2)
}
