// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/finished/commands (interfaces: DebitCreator)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockDebitCreator is a mock of DebitCreator interface.
type MockDebitCreator struct {
	ctrl     *gomock.Controller
	recorder *MockDebitCreatorMockRecorder
}

// MockDebitCreatorMockRecorder is the mock recorder for MockDebitCreator.
type MockDebitCreatorMockRecorder struct {
	mock *MockDebitCreator
}

// NewMockDebitCreator creates a new mock instance.
func NewMockDebitCreator(ctrl *gomock.Controller) *MockDebitCreator {
	mock := &MockDebitCreator{ctrl: ctrl}
	mock.recorder = &MockDebitCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebitCreator) EXPECT() *MockDebitCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDebitCreator) Create(arg0 context.Context, arg1 *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDebitCreatorMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDebitCreator)(nil).Create), arg0, arg1)
}
