// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/server/services (interfaces: OrderStateMachineContainer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
	entities "github.com/vysogota0399/gophermart_billing/internal/server/entities"
)

// MockOrderStateMachineContainer is a mock of OrderStateMachineContainer interface.
type MockOrderStateMachineContainer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStateMachineContainerMockRecorder
}

// MockOrderStateMachineContainerMockRecorder is the mock recorder for MockOrderStateMachineContainer.
type MockOrderStateMachineContainerMockRecorder struct {
	mock *MockOrderStateMachineContainer
}

// NewMockOrderStateMachineContainer creates a new mock instance.
func NewMockOrderStateMachineContainer(ctrl *gomock.Controller) *MockOrderStateMachineContainer {
	mock := &MockOrderStateMachineContainer{ctrl: ctrl}
	mock.recorder = &MockOrderStateMachineContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStateMachineContainer) EXPECT() *MockOrderStateMachineContainerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderStateMachineContainer) Create(arg0 context.Context, arg1 entities.OrderFsmOption) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderStateMachineContainerMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderStateMachineContainer)(nil).Create), arg0, arg1)
}
