// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/server/services (interfaces: WithdrawRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockWithdrawRepository is a mock of WithdrawRepository interface.
type MockWithdrawRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawRepositoryMockRecorder
}

// MockWithdrawRepositoryMockRecorder is the mock recorder for MockWithdrawRepository.
type MockWithdrawRepositoryMockRecorder struct {
	mock *MockWithdrawRepository
}

// NewMockWithdrawRepository creates a new mock instance.
func NewMockWithdrawRepository(ctrl *gomock.Controller) *MockWithdrawRepository {
	mock := &MockWithdrawRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawRepository) EXPECT() *MockWithdrawRepositoryMockRecorder {
	return m.recorder
}

// BalanceForUpdate mocks base method.
func (m *MockWithdrawRepository) BalanceForUpdate(arg0 context.Context, arg1 int64, arg2 *sql.Tx) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BalanceForUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BalanceForUpdate indicates an expected call of BalanceForUpdate.
func (mr *MockWithdrawRepositoryMockRecorder) BalanceForUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BalanceForUpdate", reflect.TypeOf((*MockWithdrawRepository)(nil).BalanceForUpdate), arg0, arg1, arg2)
}

// BeginTX mocks base method.
func (m *MockWithdrawRepository) BeginTX(arg0 context.Context, arg1 *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTX", arg0, arg1)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTX indicates an expected call of BeginTX.
func (mr *MockWithdrawRepositoryMockRecorder) BeginTX(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTX", reflect.TypeOf((*MockWithdrawRepository)(nil).BeginTX), arg0, arg1)
}

// CommitTX mocks base method.
func (m *MockWithdrawRepository) CommitTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTX indicates an expected call of CommitTX.
func (mr *MockWithdrawRepositoryMockRecorder) CommitTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTX", reflect.TypeOf((*MockWithdrawRepository)(nil).CommitTX), arg0)
}

// CreateTX mocks base method.
func (m *MockWithdrawRepository) CreateTX(arg0 context.Context, arg1 *models.Transaction, arg2 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTX", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTX indicates an expected call of CreateTX.
func (mr *MockWithdrawRepositoryMockRecorder) CreateTX(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTX", reflect.TypeOf((*MockWithdrawRepository)(nil).CreateTX), arg0, arg1, arg2)
}

// RollbackTX mocks base method.
func (m *MockWithdrawRepository) RollbackTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTX indicates an expected call of RollbackTX.
func (mr *MockWithdrawRepositoryMockRecorder) RollbackTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTX", reflect.TypeOf((*MockWithdrawRepository)(nil).RollbackTX), arg0)
}
