// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/finished (interfaces: AccrualFinishedEventsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockAccrualFinishedEventsRepository is a mock of AccrualFinishedEventsRepository interface.
type MockAccrualFinishedEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualFinishedEventsRepositoryMockRecorder
}

// MockAccrualFinishedEventsRepositoryMockRecorder is the mock recorder for MockAccrualFinishedEventsRepository.
type MockAccrualFinishedEventsRepositoryMockRecorder struct {
	mock *MockAccrualFinishedEventsRepository
}

// NewMockAccrualFinishedEventsRepository creates a new mock instance.
func NewMockAccrualFinishedEventsRepository(ctrl *gomock.Controller) *MockAccrualFinishedEventsRepository {
	mock := &MockAccrualFinishedEventsRepository{ctrl: ctrl}
	mock.recorder = &MockAccrualFinishedEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualFinishedEventsRepository) EXPECT() *MockAccrualFinishedEventsRepositoryMockRecorder {
	return m.recorder
}

// ReserveEvent mocks base method.
func (m *MockAccrualFinishedEventsRepository) ReserveEvent(arg0 context.Context, arg1 string) (*models.AccrualEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveEvent", arg0, arg1)
	ret0, _ := ret[0].(*models.AccrualEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveEvent indicates an expected call of ReserveEvent.
func (mr *MockAccrualFinishedEventsRepositoryMockRecorder) ReserveEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveEvent", reflect.TypeOf((*MockAccrualFinishedEventsRepository)(nil).ReserveEvent), arg0, arg1)
}

// SetState mocks base method.
func (m *MockAccrualFinishedEventsRepository) SetState(arg0 context.Context, arg1, arg2 string, arg3 ...*sql.Tx) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetState", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockAccrualFinishedEventsRepositoryMockRecorder) SetState(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockAccrualFinishedEventsRepository)(nil).SetState), varargs...)
}
