// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_inbox/accrual_events/failed/commands (interfaces: AccrualFailder)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
	entities "github.com/vysogota0399/gophermart_billing/internal/server/entities"
)

// MockAccrualFailder is a mock of AccrualFailder interface.
type MockAccrualFailder struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualFailderMockRecorder
}

// MockAccrualFailderMockRecorder is the mock recorder for MockAccrualFailder.
type MockAccrualFailderMockRecorder struct {
	mock *MockAccrualFailder
}

// NewMockAccrualFailder creates a new mock instance.
func NewMockAccrualFailder(ctrl *gomock.Controller) *MockAccrualFailder {
	mock := &MockAccrualFailder{ctrl: ctrl}
	mock.recorder = &MockAccrualFailderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualFailder) EXPECT() *MockAccrualFailderMockRecorder {
	return m.recorder
}

// CostAccrualFailed mocks base method.
func (m *MockAccrualFailder) CostAccrualFailed(arg0 context.Context, arg1 entities.OrderFsmOption) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CostAccrualFailed", arg0, arg1)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CostAccrualFailed indicates an expected call of CostAccrualFailed.
func (mr *MockAccrualFailderMockRecorder) CostAccrualFailed(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CostAccrualFailed", reflect.TypeOf((*MockAccrualFailder)(nil).CostAccrualFailed), arg0, arg1)
}
