// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_outbox/order_events/updated (interfaces: OrderUpdatedEventsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockOrderUpdatedEventsRepository is a mock of OrderUpdatedEventsRepository interface.
type MockOrderUpdatedEventsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUpdatedEventsRepositoryMockRecorder
}

// MockOrderUpdatedEventsRepositoryMockRecorder is the mock recorder for MockOrderUpdatedEventsRepository.
type MockOrderUpdatedEventsRepositoryMockRecorder struct {
	mock *MockOrderUpdatedEventsRepository
}

// NewMockOrderUpdatedEventsRepository creates a new mock instance.
func NewMockOrderUpdatedEventsRepository(ctrl *gomock.Controller) *MockOrderUpdatedEventsRepository {
	mock := &MockOrderUpdatedEventsRepository{ctrl: ctrl}
	mock.recorder = &MockOrderUpdatedEventsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUpdatedEventsRepository) EXPECT() *MockOrderUpdatedEventsRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockOrderUpdatedEventsRepository) BeginTx(arg0 context.Context, arg1 *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", arg0, arg1)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockOrderUpdatedEventsRepositoryMockRecorder) BeginTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockOrderUpdatedEventsRepository)(nil).BeginTx), arg0, arg1)
}

// CommitTX mocks base method.
func (m *MockOrderUpdatedEventsRepository) CommitTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTX indicates an expected call of CommitTX.
func (mr *MockOrderUpdatedEventsRepositoryMockRecorder) CommitTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTX", reflect.TypeOf((*MockOrderUpdatedEventsRepository)(nil).CommitTX), arg0)
}

// ReserveNewOrderEvent mocks base method.
func (m *MockOrderUpdatedEventsRepository) ReserveNewOrderEvent(arg0 context.Context, arg1 string, arg2 *sql.Tx) (*models.OrderEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveNewOrderEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.OrderEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveNewOrderEvent indicates an expected call of ReserveNewOrderEvent.
func (mr *MockOrderUpdatedEventsRepositoryMockRecorder) ReserveNewOrderEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveNewOrderEvent", reflect.TypeOf((*MockOrderUpdatedEventsRepository)(nil).ReserveNewOrderEvent), arg0, arg1, arg2)
}

// RollbackTX mocks base method.
func (m *MockOrderUpdatedEventsRepository) RollbackTX(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTX", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTX indicates an expected call of RollbackTX.
func (mr *MockOrderUpdatedEventsRepositoryMockRecorder) RollbackTX(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTX", reflect.TypeOf((*MockOrderUpdatedEventsRepository)(nil).RollbackTX), arg0)
}

// Send mocks base method.
func (m *MockOrderUpdatedEventsRepository) Send(arg0 context.Context, arg1 *models.OrderEvent, arg2 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockOrderUpdatedEventsRepositoryMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOrderUpdatedEventsRepository)(nil).Send), arg0, arg1, arg2)
}
