// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/gophermart_billing/internal/transaction_outbox/orders/updated (interfaces: OrderUpdatedEventsPublisher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vysogota0399/gophermart_billing/internal/models"
)

// MockOrderUpdatedEventsPublisher is a mock of OrderUpdatedEventsPublisher interface.
type MockOrderUpdatedEventsPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUpdatedEventsPublisherMockRecorder
}

// MockOrderUpdatedEventsPublisherMockRecorder is the mock recorder for MockOrderUpdatedEventsPublisher.
type MockOrderUpdatedEventsPublisherMockRecorder struct {
	mock *MockOrderUpdatedEventsPublisher
}

// NewMockOrderUpdatedEventsPublisher creates a new mock instance.
func NewMockOrderUpdatedEventsPublisher(ctrl *gomock.Controller) *MockOrderUpdatedEventsPublisher {
	mock := &MockOrderUpdatedEventsPublisher{ctrl: ctrl}
	mock.recorder = &MockOrderUpdatedEventsPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUpdatedEventsPublisher) EXPECT() *MockOrderUpdatedEventsPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockOrderUpdatedEventsPublisher) Publish(arg0 context.Context, arg1 *models.OrderEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockOrderUpdatedEventsPublisherMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockOrderUpdatedEventsPublisher)(nil).Publish), arg0, arg1)
}
